easy_admin:
    site_name: 'Wild Circus.'
    user:
        display_name: true
        display_avatar: false
    entities:
        creatures:
            class: App\Entity\creature
            list:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'power', label: 'Pouvoir' }
                    - { property: 'image', type: 'image', label: 'Image', base_path: '%app.path.creature_images%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.creature_images%' }
            form:
                fields:
                    - { property: 'name', label: 'Nom', type: 'text' }
                    - { property: 'power', label: 'Pouvoir', type: 'text' }
                    - { property: 'imageFile', type: 'file' }