vich_uploader:
    db_driver: orm
    mappings:
            creatures_images:
                uri_prefix:         '%app.path.creature_images%'
                upload_destination: '%kernel.project_dir%/public/upload/%app.path.creature_images%'
